passes:
    - !require '../../Compiler/ContainerAware'

services:
    http_kernel:
        class: !require '../../HttpKernel'
        arguments:
            - '@kernel'
            - '@router'
            - '@logger'

    config:
        class: !require '../../Config'
        arguments:
            - '@kernel'

    router:
        class: !require '../../Routing/Router'

    logger:
        class: !require '../../Logger/Logger'
        arguments:
            - '@container'

    core.annotation.route:
        class: !require '../../Annotation/Route'
        tags: ['annotation']
        arguments:
            - '@container'
            - '@router'

    core.annotation.method:
        class: !require '../../Annotation/Method'
        tags: ['annotation']
        arguments:
            - '@container'
            - '@router'
