passes:
    - !require '@SwigBundle://Compilers/SetSwigRenderer'

services:
    swig:
        class: !require '@SwigBundle://Swig/Renderer'
        tags: ['renderer']
        arguments:
            - '@container'