passes:
    - !require '@SwigBundle://Compilers/SetSwigRenderer'

services:
    swig:
        class: !require '@SwigBundle://Swig/Renderer'
        tags: ['renderer']
        arguments:
            - '@container'

    swig.extension.default:
        class: !require '@SwigBundle://Swig/DefaultExtension'
        tags: ['swig.extension']
        arguments:
            - '@container'